require 'rake/testtask'

Rake::TestTask.new do |t|
  t.test_files = FileList.new("test/models/*_test.rb", "test/*_test.rb")
end

Rake::TestTask.new(:integration_test) do |t|
  t.pattern = "test/integration/*_test.rb"
end
