source 'https://rubygems.org'
ruby "2.0.0"

gem 'sinatra'
gem 'rack-flash3'
gem 'cf-app-utils', git: "https://github.com/cloudfoundry/cf-app-utils-ruby"
gem 'rake'

group :test do
  gem 'rack-test'
  gem 'mocha', require: false
  gem 'rerun'
  gem 'capybara'
  gem 'capybara_minitest_spec'
  gem 'octokit'
  gem 'pry'
end